require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - 'config/**/*.rb'
    - 'bin/**/*'
    - 'test/**/*'
    - 'db/**/*'

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
